### ISSUE TITLE
Text eval without training

### ISSUE THREAD

**Issue by daniellawson9999** [ManifoldRG/NEKO#23]
We want  to do text eval  without updating a model, e.g. loading a pretrained and doing evaluation without doing training steps. I do this with eval.py for control,  need to update eval.py similarly for text. @bhavul

**Comment by SasankYadati** [comment]
hello @daniellawson9999 @bhavul, I'd like to work on this issue. If there's any pointers that could help me please let me know? I could go through the eval.py as a start.

**Comment by bhavul** [comment]
Hey @SasankYadati that'd be great. First of all, it's always good for anyone to skim through or watch some video / blog on Gato paper by DeepMind, since neko's implementation has inspiration taken from there. It would make terminologies more clear that we use quite commonly in the codebase. It's meant to be a generalist model and complete different kinds of tasks (control tasks, text tasks such as generation, image tasks such as captioning, vqa, etc). 

For this issue, I'd say have a go through the code changes done to introduce text modality here : https://github.com/ManifoldRG/NEKO/pull/1

You can skim through and just try it out yourself by loading code in vscode, or on an instance. The command to run text training is given there.

**The purpose that `eval.py` serves is to load an existing checkpoint of a model, and just run inference with it. This was done for control tasks, but hasn't been for text modality.**

If you [check here](https://github.com/ManifoldRG/NEKO/pull/1/files#diff-fdeb1037705547875af845e42b08d1830669a091c3caf887417166aace10e0f5R60), the `evaluate` method in text_task already covers how evaluation works. However, it only runs right now while training the model, on the validation dataset provided during training.

What needs to be done for eval.py is to provide same sort of evaluation mechanism on any dataset we provide (we could start with 1-2 huggingface based text datasets to begin with like wikitext, openwebtext, etc.) and any checkpoint of model we provide via CLI args. 

Hope this helps. Feel free to ask any questions you may have further. Also, if you're committed to working on it, do assign yourself the issue. :)

**Comment by SasankYadati** [comment]
Thank you @bhavul. I am unable to assign the issue to myself. I will start working on this item though.

**Comment by SasankYadati** [comment]
@bhavul is this project meant to be run on a particular os/host? I am assuming not. The ```env.yml``` file has host specific builds for some dependencies (eg: numpy=1.24.3=py310h5f9d8c6_1) which is valid for Linux only (https://anaconda.org/anaconda/numpy/files?version=1.24.3&page=0&channel=main). This is causing ```conda env create -f env.yml``` to fail on my machine with ResolvePackageNotFound. Please see https://github.com/conda/conda/issues/7311#issuecomment-442320274 for some more info.

Would it be possible for you to export the env file with ```--no-builds``` option so it works on other machines as well?

**Comment by bhavul** [comment]
Have you got windows or mac? It works fine on mac. 
The original environment was created by @daniellawson9999, who had committed this via linux machine. I believe
Another core member (@henryj18) has tested it on windows too. 

So the project can work for text and image modalities on all the systems. 
I think control datasets *only* install on linux as of now, so you may not be able to trigger a control task run working on mac / windows since datasets would not install/work.

Unfortunately, I don't have my laptop around with me right now. 
My suggestion for now would be to unblock yourself by installing any/latest numpy. It should work fine. Think similarly for other extensions too if they cause any errors. 

Also do create a small issue for this, so it gets taken care of soon. Thanks for reporting.

**Comment by SasankYadati** [comment]
Thank you @bhavul. I opened one [here](https://github.com/ManifoldRG/NEKO/issues/64). I will install deps manually for now to unblock myself.

EDIT: I am using Windows btw.

**Comment by SasankYadati** [comment]
@bhavul can you please take a look and let me know what you think!

**Comment by SasankYadati** [comment]
Can we close this issue? Anything else I need to look into? @bhavul

**Comment by bhavul** [comment]
No, we can close this.
