### ISSUE TITLE
Investigate Alternative Datasets: M3W

### ISSUE THREAD

**Issue by atharva-tendle** [ManifoldRG/NEKO#52]
**Goal:**
----------------
We want to investigate the M3W dataset and find alternatives to this dataset. 
This investigation should consider the following aspects regarding the dataset:
- Nature of the dataset in terms of compatibility
- Size
- Memory Requirements (if possible)
- Ease of Integration

Use this [link](https://docs.google.com/spreadsheets/d/18t38QKIMsZXiNxRcgDdKIxcrclPb5QEzvVKvGQBSJ98/edit#gid=1513169105) as a starting point.

**Output:**
----------------
Come up with a dataset proposal for an alternative to the M3W dataset and get it reviewed by the team.

**Comment by BobakBagheri** [comment]
Adding @snat-s for addition to current dataset organization effort

**Comment by BobakBagheri** [comment]
Closing, dataset reconciliation effort is captured in #56 so refer to this for all dataset related issues

**Comment by snat-s** [comment]
I am going to give some context, even though we have closed this issue on what M3W alternatives would be a good idea.

| Dataset Name      | # Documents |# Images | # tokens| Size (GB) |
| ------------------------- | -------------------- |--------------| -------------|----------------|
| MMC4                    | 101.2M   |571M |43B|1.8Tb~|
| Multimodal C4 fewer-faces (mmc4-ff)    |77.7M |375M|33B|15 GB|
|mmc4 core fewer-faces (mmc4-core-ff)|7.3M |29.9M|2.4B|1GB~|
|mmc4 core (mmc4-core)|5.5M|22.4M |1.8B |1.3GB~|
|OBELICS| 141M|353M|115B|738GB|

The sizes of OBELICS and of mmc4 are estimates because it seems that there is no public size available. You only have available the links to the images and the text they contain. So this are just estimates. 
For mmc4  I supposed that they scale lineraly. I actually don't know the size but did an estimate with this dataset: [MMC4-130k-image-english](https://huggingface.co/datasets/silk-road/MMC4-130k-image-english).
The only one that I could find was [this](https://github.com/allenai/mmc4/issues/6) issue that talked about the massive size of mmc4.
